apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: function-helloworld-http
  name: function-helloworld-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: function-helloworld-http
  template:
    metadata:
      labels:
        app: function-helloworld-http
    spec:
      containers:
        - image: alpine:3.13.5
          name: alpine
          command: ['sh', '-c', 'sleep 365d']
