apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: scale-example-workload
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          example-workload
  pollingInterval: 3
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 5
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
          - type: Pods
            value: 1
            periodSeconds: 3
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 1
            periodSeconds: 3
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.ingress-nginx.svc.cluster.local:9090
      metricName: http_requests_total
      query: increase(promhttp_metric_handler_requests_total{namespace="keda-demo", code="200"}[30s])
      threshold: '3'
