apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-so
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          example-workload
  pollingInterval: 3
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 5
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
          - type: Pods
            value: 1
            periodSeconds: 3
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Pods
            value: 1
            periodSeconds: 3
  triggers:
  - type: redis
    metadata:
      address: redis.keda-demo.svc.cluster.local:6379
      listName: mylist
      listLength: "2"
